management:
  endpoints:
    web:
      exposure:
        include: '*'
        
spring:  datasource:    url: jdbc:mysql://mysqlaws.cq23yftjp0mj.us-east-1.rds.amazonaws.com/SIMPLE
    username: AWSadmin
    password: kmreddy1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    hibernate:      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      
    
 